### DISCUSSION TITLE
:snapped-target

### DISCUSSION THREAD

**Discussion by argyleink** [argyleink/ScrollSnapExplainers#5] [General]
## Context: [explainer](https://github.com/argyleink/ScrollSnapExplainers/blob/main/css-snap-target)

Questions?
Thoughts?
Naming fine?
Risks?

**Comment by argyleink** [comment]
things to think about:
1. could be multiple matches
2. need ability to specify which axis?

**Reply by rol4nd909** [reply]
Is there any news on this feature?

> things to think about:
> 
> 1. could be multiple matches
> 2. need ability to specify which axis?

Point 1 how could there be multiple matches? With scroll-snap only one item a time will be snapped right?

PS: love that there is a nice javascript solution coming for it ;) but would be awesome to do css only like in this example

https://codepen.io/ROL4ND909/full/MWMzbog

**Reply by argyleink** [reply]
`scroll-state` queries are looking to take this role over, [check here in Canary](https://codepen.io/argyleink/pen/JjqVzxq/fbaf06eda7e1055323684be0a08087ce)

```css
  container-type: scroll-state;
  scroll-snap-align: center;
      
  @supports (container-type: scroll-state) {
    figcaption {
      transform: translateY(100%);
          
      @container scroll-state(snapped: inline) {
        transform: translateY(0);
      }
   }
}
```

**Reply by rol4nd909** [reply]
This is nice :) not sure if I found a bug or what I try is not possible. But it looks like I can't select the next sibling of a snapped item with the `~` selector.

example
```css
.slides > div {
    container-type: scroll-state;

    @container scroll-state(snapped: inline) {
      > .slide {
        // properties for snapped item
      }
      
      ~ div {
        // properties for the next sibling of snapped item
      }
    }
  }
``` 

and a codepen to show:
https://codepen.io/ROL4ND909/pen/WNqLozL/4d6bda825268281aa0af2f14b925513a
